analysis:
  description: STPA-Sec Step 1 analysis using standard single-agent approach with
    Azure OpenAI
  name: Digital Banking Platform Security Analysis - Azure GPT-4 Turbo Standard
  output_dir: ./analyses/banking-azure-gpt4-turbo-standard/
execution:
  mode: standard
input:
  path: demo/banking-analysis/system-description.txt
  type: file
model:
  name: gpt-4-turbo
  provider: openai
output:
  exports:
  - format: json
  - format: markdown
