analysis:
  description: STPA-Sec Step 1 analysis using Ollama for testing JSON fallback
  name: demo-banking 
  output_dir: ./analyses/demo
execution:
  mode: standard
input:
  path: example_systems/demo-banking/system-description.txt
  type: file
model:
  name: mixtral:instruct
  provider: ollama
  api_endpoint: http://localhost:11434
output:
  exports:
  - format: json
  - format: markdown