# Azure OpenAI GPT-4 Turbo standard Step 1 analysis configuration
#
# To use this configuration, you need to set these environment variables:
# - AZURE_OPENAI_API_KEY: Your Azure OpenAI API key
# - AZURE_OPENAI_API_BASE: Your Azure OpenAI endpoint (e.g., https://myresource.openai.azure.com/)
# - AZURE_OPENAI_API_MODEL: Your deployment name in Azure (e.g., gpt-4-turbo)
#
# The system will automatically detect and use Azure OpenAI when these are set.

analysis:
  name: "Digital Banking Platform Security Analysis - Azure GPT-4 Turbo Standard"
  description: "STPA-Sec Step 1 analysis using standard single-agent approach with Azure OpenAI"
  output_dir: "./analyses/banking-azure-gpt4-turbo-standard/"

model:
  # When Azure environment variables are set, these values are overridden
  # but we keep them for documentation purposes
  provider: "openai"  # Azure OpenAI uses the same provider
  name: "gpt-4-turbo"  # This will be overridden by AZURE_OPENAI_API_MODEL
  # No api_key_env needed - Azure credentials are detected automatically

execution:
  mode: "standard"  # Single agent per task

input:
  type: "file"
  path: "demo/banking-analysis/system-description.txt"

output:
  exports:
    - format: "json"
    - format: "markdown"