# Enhanced dual-perspective Step 1 analysis configuration

analysis:
  name: "Digital Banking Platform Security Analysis - Enhanced"
  description: "STPA-Sec Step 1 analysis using ASI-ARCH dual perspective approach"
  output_dir: "./analyses/banking-enhanced/"

model:
  provider: "openai"
  name: "gpt-4-turbo-preview"
  api_key_env: "OPENAI_API_KEY"

execution:
  mode: "enhanced"  # Dual perspective (Intuitive + Technical)
  cognitive_styles:
    - "intuitive"
    - "technical"

input:
  type: "file"
  path: "demo-banking-system.txt"

output:
  exports:
    - format: "json"
    - format: "markdown"
    - format: "csv"