# GPT-4 Turbo enhanced ASI-ARCH Step 1 analysis configuration

analysis:
  name: "Digital Banking Platform Security Analysis - GPT-4 Turbo Enhanced"
  description: "STPA-Sec Step 1 analysis using enhanced ASI-ARCH multi-agent approach with GPT-4 Turbo"
  output_dir: "./analyses/banking-gpt4-turbo-enhanced/"

model:
  provider: "openai"
  name: "gpt-4-turbo-preview"
  api_key_env: "OPENAI_API_KEY"

execution:
  mode: "enhanced"  # ASI-ARCH multi-agent approach with cognitive styles

input:
  type: "file"
  path: "demo/banking-analysis/system-description.txt"

output:
  exports:
    - format: "json"
    - format: "markdown"