# Standard single-agent Step 1 analysis configuration

analysis:
  name: "Digital Banking Platform Security Analysis - Standard"
  description: "STPA-Sec Step 1 analysis using standard single-agent approach"
  output_dir: "./analyses/banking-standard/"

model:
  provider: "ollama"  # Start with local model for testing
  name: "llama2"     # or whatever model you have locally
  # api_key_env: "OPENAI_API_KEY"  # Not needed for Ollama

execution:
  mode: "standard"  # Single agent per task

input:
  type: "file"
  path: "demo-banking-system.txt"

output:
  exports:
    - format: "json"
    - format: "markdown"