# Test configuration for standard Step 1 analysis with Ollama Mixtral
analysis:
  name: "Digital Banking Platform - Standard Analysis (Ollama)"
  description: "Test run of Step 1 STPA-Sec analysis using Ollama Mixtral:instruct"
  output_dir: "./analyses/banking-ollama-standard"

model:
  provider: "ollama"
  name: "mixtral:instruct"
  api_endpoint: "http://localhost:11434"
  temperature: 0.7
  max_tokens: 4096

execution:
  mode: "standard"  # Single agent per task
  timeout: 300      # 5 minutes per agent
  retry_count: 2
  retry_delay: 5

input:
  type: "file"
  path: "./demo-banking-system.txt"

output:
  formats:
    - json
    - markdown
  include_logs: true
  include_raw_responses: false

validation:
  check_completeness: true
  min_losses: 3
  min_hazards: 3
  min_stakeholders: 3