# Test configuration for standard Step 1 analysis with GPT-4 Turbo
analysis:
  name: "Digital Banking Platform - Standard Analysis (GPT-4)"
  description: "Test run of Step 1 STPA-Sec analysis using standard single-agent approach"
  output_dir: "./analyses/banking-gpt4-standard"

model:
  provider: "openai"
  name: "gpt-4-turbo-preview"
  api_key_env: "OPENAI_API_KEY"
  temperature: 0.7
  max_tokens: 4096

execution:
  mode: "standard"  # Single agent per task
  timeout: 300      # 5 minutes per agent
  retry_count: 2
  retry_delay: 5

input:
  type: "file"
  path: "./demo-banking-system.txt"

output:
  formats:
    - json
    - markdown
  include_logs: true
  include_raw_responses: false

validation:
  check_completeness: true
  min_losses: 3
  min_hazards: 3
  min_stakeholders: 3